<?php

use Illuminate\Database\Seeder;

class ProjectTableSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		// AuthorTableSeeder is handling me just fine, initially... :)
		$projects = App\Project::all();

		$this->attachAuthors($projects);
		$this->attachCategories($projects);
		$this->modifyPermalink($projects);
	}

	/**
	 * Randomly attach more authors to some projects
	 * @param  object $projects collection of projects
	 * @return void           sets data in the database
	 */
	public function attachAuthors($projects) {
		$authors = App\Author::all()->pluck('id');

		$project_ids = $projects->pluck('id');

		foreach ($projects as $project) {
			$author = $authors->random();

			$isDuplicate = DB::table('author_project')
				->where('author_id', $author)
				->where('project_id', $project->id)
				->get();

			if (rand(0,1) >= 1 && empty(json_decode($isDuplicate))) {
				$project->authors()->attach($author);
			}
		}
	}

	/**
	 * Attach random categories to projects
	 * @param  object $projects collection of projects
	 * @return void           sets data in the database
	 */
	public function attachCategories($projects) {
		$categories = App\Category::all()->pluck('id');

		foreach ($projects as $project) {
			$project->categories()->attach($categories->random(rand(1,2)));
		}
	}

	/**
	 * Modifies the pre-existing permalink which was generated by the factory
	 * to prefix with the id and a '-' separator
	 * @param  object $projects collection of projects
	 * @return void           sets data in the database
	 */
	public function modifyPermalink($projects) {

		foreach ($projects as $project) {
			$old_permalink = $project->permalink;
			$project_id = $project->id;

			$new_permalink = $project_id . '-' . $old_permalink;

			DB::table('projects')
				->where('id', $project_id)
				->update(['permalink' => $new_permalink]);
		}
	}
}
